# Generated by Django 4.1 on 2022-08-26 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
