# Generated by Django 4.1 on 2022-08-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritos',
            old_name='anime',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='anime',
            new_name='product',
        ),
    ]
